CakeShop/Controllers/CakeController.cs
using CakeShop.Core.Models;
using CakeShop.Core.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CakeShop.Controllers
{
    [Route("/cakes")]
    public class CakeController : Controller
    {
        private readonly ICakeRepository _cakeRepository;
        private readonly ICategoryRepository _categoryRepository;

        public CakeController(ICakeRepository cakeRepository, ICategoryRepository categoryRepository)
        {
            _cakeRepository = cakeRepository;
            _categoryRepository = categoryRepository;
        }

        [HttpGet("{category?}")]
        public async Task<IActionResult> List(string category)
        {
            var selectedCategory = !string.IsNullOrWhiteSpace(category) ? category : null;
            var cakesListViewModel = new CakesListViewModel
            {
                Cakes = await _cakeRepository.GetCakes(selectedCategory),
                CurrentCategory = selectedCategory ?? "All Cakes"
            };
            return View(cakesListViewModel);
        }

        [HttpGet("details/{id}")]
        public async Task<IActionResult> Details(int id)
        {

            var cake = await _cakeRepository.GetCakeById(id);

            return View(cake);
        }
    }
}

CakeShop/Controllers/ShoppingCartController.cs
using CakeShop.Core.Models;
using CakeShop.Core.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CakeShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly ICakeRepository _cakeRepository;
        private readonly IShoppingCartService _shoppingCart;

        public ShoppingCartController(ICakeRepository cakeRepository, IShoppingCartService shoppingCart)
        {
            _cakeRepository = cakeRepository;
            _shoppingCart = shoppingCart;
        }

        public async Task<IActionResult> Index()
        {
            await _shoppingCart.GetShoppingCartItemsAsync();
            var shoppingCartCountTotal = await _shoppingCart.GetCartCountAndTotalAmmountAsync();
            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartItemsTotal = shoppingCartCountTotal.ItemCount,
                ShoppingCartTotal = shoppingCartCountTotal.TotalAmmount,
            };


            return View(shoppingCartViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddToShoppingCart(int cakeId)
        {
            var selectedCake = await _cakeRepository.GetCakeById(cakeId);
            if (selectedCake == null)
            {
                return NotFound();
            }

            await _shoppingCart.AddToCartAsync(selectedCake);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFromShoppingCart(int cakeId)
        {
            var selectedCake = await _cakeRepository.GetCakeById(cakeId);
            if (selectedCake == null)
            {
                return NotFound();
            }

            await _shoppingCart.RemoveFromCartAsync(selectedCake);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveAllCart()
        {
            await _shoppingCart.ClearCartAsync();
            return RedirectToAction("Index");
        }
    }
}

CakeShop/Views/Cake/Details.cshtml
@model Cake
@{
    ViewData["Title"] = "Details";
}
<h2>@Model.Name</h2>
<br />
<div class="row">
    <div class="col-md-6">
        <img class="img-thumbnail" src="@Model.ImageUrl" alt="@Model.Name" />
        <p></p>
    </div>
    <div class="col-md-6">
        <h4>@Model.Name</h4>
        <p><i>@Model.Price.ToString("c")</i></p>
        <p>@Model.ShortDescription</p>
        <p>@Model.LongDescription</p>
        <form asp-action="AddToShoppingCart"
              asp-controller="ShoppingCart"
              asp-route-cakeId="@Model.Id"
              method="post">

            <button class="btn btn-primary buy-now-btn">Add to Cart</button>
        </form>

    </div>
</div>

CakeShop/Views/Cake/List.cshtml
@model CakesListViewModel

@if (Model.Cakes?.Count() > 0)
{
    <h1>@Model.CurrentCategory</h1>
    <div class="row">
        @foreach (var cake in Model.Cakes)
        {
            @await Html.PartialAsync("CakeView", cake);
        }
    </div>
}
else
{
    <h1>Cakes</h1>
    <p>Sorry! Not cakes are found in '@Model.CurrentCategory' category. </p>
}